import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { cn } from '~/lib/utils';
import './globals.css';

const font = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: {
    default: 'Lailla.io :: Aproximando você de seus clientes!',
    template: '%s | Lailla.io',
  },
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang='en' className='h-full'>
      <body className={cn('h-full', font.className)}>{children}</body>
    </html>
  );
};

export default RootLayout;
